name: Docker Compose and Playwright Tests

on:
  workflow_call:

    secrets:
      BACKEND_PORT:
        required: true
      FRONTEND_PORT:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
    steps:
      - name: Run Playwright Tests
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}

          
        run: |
          python "Playwright/run_tests.py"

      