name: Docker Compose and Playwright Tests

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        default: "3.11"
        type: string
      test-script:
        description: "Path to the Playwright test script"
        default: "Playwright/run_tests.py"
        type: string


env: 
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Run Playwright Tests
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
          # DJANGO_SETTINGS_MODULE: Backend.controller.main_frame_project.settings
          DJANGO_ALLOW_ASYNC_UNSAFE: 1 
          BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
          FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
        run: |
          python ${{ inputs.test-script }}

      