name: Docker Compose and Playwright Tests

on:
  workflow_dispatch:
    inputs:
      BACKEND_PORT:
        required: true
      FRONTEND_PORT:
        required: true
      python-version:
        required: true
      test-script:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
    timeout-minutes: 15

    steps:
      - name: Checkout External Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure Browsers Are Installed
        run: python -m playwright install --with-deps

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$PWD:$PYTHONPATH" >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Run Playwright Tests
        run: python ${{ inputs.test-script }}
