name: Docker Compose and Playwright Tests

on:
  push:
  workflow_dispatch:
    inputs:
      python-version:
        description: "Python version to use"
        default: "3.11"
        type: string
      test-script:
        description: "Path to the Playwright test script in the external repository"
        default: "Playwright/run_tests.py"
        type: string

      BACKEND_PORT:
        required: true
      FRONTEND_PORT:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
    timeout-minutes: 15
    container:
      image: python:${{ inputs.python-version }}  # Use the Python version specified in inputs
      options: --ipc=host  # Ensures Playwright can run in the container

    steps:
      - name: Checkout External Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Playwright/requirements.txt

      - name: Ensure Browsers Are Installed
        run: python -m playwright install --with-deps

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$PWD:$PYTHONPATH" >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Run Playwright Tests
        run: python ${{ inputs.test-script }}
